# Choose whether to broadcast the message to everyone, or just the joining player
broadcast_publicly: true

# Choose whether or not to enable the vanilla join message
vanilla_join_message: false

# Choose whether to welcome only newcomers, or all players on join
newcomers_only: false

# Text that should be prefixed to the player's name (perfect for formatting)
# Feel free to use Minecraft's formatting codes (e.g. &0, &1, ..., &f)
player_name_prefix: "&4"

# Added after welcome message when newcomers join
# Feel free to use Minecraft's formatting codes (e.g. &0, &1, ..., &f)
newcomer_message: "&6%player% is new! Welcome them to the server!"

# List of possible welcome messages
# Use %player% for the player's name
# Feel free to use Minecraft's formatting codes (e.g. &0, &1, ..., &f)
messages:
  - "&6Howdy Doody, %player%! Welcome to the server!"
  - "&6Welcome, %player%! We were expecting you ( ͡° ͜ʖ ͡°)"
  - "&6Welcome, %player%! We hope you brought pizza."
  - "&6Welcome, %player%! Leave your weapons by the door."
  - "&6A wild %player% appeared."
  - "&6%player% is here, as the prophecy foretold."
  - "&6Brace yourselves. %player% just joined the server."
  - "&6%player% just joined. Hide your bananas."
  - "&6Welcome %player%, watch out for the harbormaster!"
  - "&6&kBlahblah %player%, blahb bla bla bla blahblahbl!"